
namespace peajeWebApp.Models.DatosStoreProcedure
{
    public class DatosGuardarDoc
    {
        public string NumeroDocumentoEmisor { get; set; }
        public string SerieNumero { get; set; }
        public string TipoDocumento { get; set; }
        public string TipoDocumentoEmisor { get; set; }
        public string BL_EstadoRegistro { get; set; }
        public int BL_Reintento { get; set; }
        public string BL_Origen { get; set; }
        public int BL_HASFileResponse { get; set; }
        public string CorreoAdquiriente { get; set; }
        public string CorreoEmisor { get; set; }
        public string DepartamentoEmisor { get; set; }
        public string DireccionEmisor { get; set; }
        public string DistritoEmisor { get; set; }
        public string FechaEmision { get; set; }
        public string NombreComercialEmisor { get; set; }
        public string NumeroDocumentoAdquiriente { get; set; }
        public string PaisEmisor { get; set; }
        public string ProvinciaEmisor { get; set; }
        public string RazonSocialAdquiriente { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string SerieNumeroAfectado { get; set; }
        public string CodigoLeyenda_1 { get; set; }
        public string TextoLeyenda_1 { get; set; }
        public string TipoDocumentoAdquiriente { get; set; }
        public string TipoMoneda { get; set; }
        public string TotalIGV { get; set; }
        public string TotalISC { get; set; }
        public string TotalOtrosCargos { get; set; }
        public string TotalOtrosTributos { get; set; }
        public string TotalValorVentaNetoOpExonerada { get; set; }
        public string TotalValorVentaNetoOpGratuitas { get; set; }
        public string TotalValorVentaNetoOpGravadas { get; set; }
        public string TotalValorVentaNetoOpNoGravada { get; set; }
        public string TotalvalorVentaNetoOpExporta { get; set; }
        public string TotalVenta { get; set; }
        public string UbigeoEmisor { get; set; }
        public string Urbanizacion { get; set; }
        public string TipoDocumentoAfectado { get; set; }
        public string MotivoNCND { get; set; }
        public string TipoNCND { get; set; }
        public string Tipocambio { get; set; }
        public string DireccionAdquiriente { get; set; }
        public string TotalImpuestos { get; set; }
        public string CodigoAuxiliar40_1 { get; set; }
        public string TextoAuxiliar40_1 { get; set; }
        public string TipoOperacion { get; set; }
        public string HoraEmision { get; set; }
        public string CodigoLocalAnexoEmisor { get; set; }
        public string GuiaRemision { get; set; }
        public string OrdenCompra { get; set; }
        public string TipoGuiaRemision { get; set; }
        public string Formapago { get; set; }
        public string UbigeoAdquiriente { get; set; }
        public string UrbanizacionAdquiriente { get; set; }
        public string ProvinciaAdquiriente { get; set; }
        public string DepartamentoAdquiriente { get; set; }
        public string DistritoAdquiriente { get; set; }
        public string PaisAdquiriente { get; set; }
        public string CodigoDescuento { get; set; }
        public string MontoBaseDescuentoGlobal { get; set; }
        public string PorcentajeDsctoGlobal { get; set; }
        public string DescuentosGlobales { get; set; }
        public string TotalDescuentos { get; set; }
        public string CodigoDetraccion { get; set; }
        public string PorcentajeDetraccion { get; set; }
        public string TotalDetraccion { get; set; }
        public string BancoNacion { get; set; }
        public string CodigoFormaAnticipo { get; set; }
        public string PorcentajePercepcion { get; set; }
        public string TotalVentaConPercepcion { get; set; }
        public string BaseImponiblePercepcion { get; set; }
        public string RegimenPercepcion { get; set; }
        public string TotalPercepcion { get; set; }
        public string TotalRetencion { get; set; }
        public string PorcentajeRetencion { get; set; }
        public string TotalDocumentoAnticipo { get; set; }
        public string TotalDsctoGlobalesAnticipo { get; set; }
        public string PorcentajeDsctoGlobalAnticipo { get; set; }
        public string CodigoSerieNumeroAfectado { get; set; }
        public string Textoleyenda_2 { get; set; }
        public string FacturaPagoNegociable { get; set; }
        public string MontoNetoPendiente { get; set; }
        public string MontoPagoCuota1 { get; set; }
        public string MontoPagoCuota2 { get; set; }
        public string MontoPagoCuota3 { get; set; }
        public string MontoPagoCuota4 { get; set; }
        public string MontoPagoCuota5 { get; set; }
        public string MontoPagoCuota6 { get; set; }
        public string MontoPagoCuota7 { get; set; }
        public string MontoPagoCuota8 { get; set; }
        public string MontoPagoCuota9 { get; set; }
        public string MontoPagoCuota10 { get; set; }
        public string MontoPagoCuota11 { get; set; }
        public string MontoPagoCuota12 { get; set; }
        public string FechaPagoCuota1 { get; set; }
        public string FechaPagoCuota2 { get; set; }
        public string FechaPagoCuota3 { get; set; }
        public string FechaPagoCuota4 { get; set; }
        public string FechaPagoCuota5 { get; set; }
        public string FechaPagoCuota6 { get; set; }
        public string FechaPagoCuota7 { get; set; }
        public string FechaPagoCuota8 { get; set; }
        public string FechaPagoCuota9 { get; set; }
        public string FechaPagoCuota10 { get; set; }
        public string FechaPagoCuota11 { get; set; }
        public string FechaPagoCuota12 { get; set; }
        public string TextoAuxiliar250_1 { get; set; }
        public string TextoAuxiliar250_2 { get; set; }
        public string TextoAuxiliar250_3 { get; set; }
        public string TextoAuxiliar250_4 { get; set; }
        public string TextoAuxiliar250_5 { get; set; }
        public string TextoAuxiliar250_6 { get; set; }
        public string TextoAuxiliar250_7 { get; set; }
        public string TextoAuxiliar250_8 { get; set; }
        public string TextoAuxiliar250_9 { get; set; }
        public string TextoAuxiliar250_10 { get; set; }
        public string TextoAuxiliar250_11 { get; set; }
        public string TextoAuxiliar250_12 { get; set; }
        public string TextoAuxiliar250_13 { get; set; }
        public string TextoAuxiliar250_14 { get; set; }
        public string TextoAuxiliar250_15 { get; set; }
        public string TextoAuxiliar250_16 { get; set; }
        public string TextoAuxiliar250_17 { get; set; }
        public string TextoAuxiliar250_18 { get; set; }
        public string TextoAuxiliar250_19 { get; set; }
        public string TextoAuxiliar250_20 { get; set; }
        public string TextoAuxiliar500_1 { get; set; }
        public string TextoAuxiliar500_2 { get; set; }
        public string TextoAuxiliar500_3 { get; set; }
        public string TextoAuxiliar500_4 { get; set; }
        public string MontoBaseRetencion { get; set; }
        public string Fechavencimiento { get; set; }
        public string Totalvalorventa { get; set; }
        public string Totalprecioventa { get; set; }
        public string MontoBaseIGB { get; set; }
        public List<ListaDetalleGuardarDocumento> listaDetalleGuardarDocumentos { get; set; }
    }
}
